export interface PatientInterface {
    name: string,
    address: string,
    addressNumber: number,
    birthDate: string,
    cpf: string,
    gender: string,
    id: number,
    neighborhood: string,
    phoneNumber: number,
    rg: string,
    updatedAt: string | null,
    createdAt: string,
    profession: string,
    cep: string,
    uf: string,
    guardiancpf: string,
    guardianName: string,
    guardianPhoneNumber: number,
}